import React from 'react';
import Link from 'next/link';

export default function JunkRemovalLanding() {
  return (
    <div className="min-h-screen bg-[#fafafa] font-sans selection:bg-indigo-100 selection:text-indigo-900">
      <nav className="border-b border-gray-200 bg-white">
        <div className="max-w-6xl mx-auto px-6 h-20 flex justify-between items-center">
          <Link href="/" className="text-xl font-extrabold text-gray-900 tracking-tighter flex items-center gap-3">
            <div className="w-10 h-10 bg-black rounded-xl flex items-center justify-center">
              <span className="text-white text-xl leading-none pt-0.5">✦</span>
            </div>
            EchoReply
          </Link>
          <Link href="/dashboard" className="px-5 py-2.5 bg-black text-white rounded-lg font-bold hover:bg-gray-800 transition-all">
            Go to Dashboard
          </Link>
        </div>
      </nav>

      <main className="max-w-6xl mx-auto px-6 py-20 md:py-32 grid md:grid-cols-2 gap-16 items-center">
        <div>
          <div className="inline-flex items-center gap-2 mb-6 px-4 py-2 rounded-full bg-emerald-50 border border-emerald-100 text-emerald-700 text-sm font-bold tracking-wide">
             <span className="w-2 h-2 rounded-full bg-emerald-500"></span> 
             Built for Local Operations
          </div>
          <h1 className="text-5xl md:text-6xl font-extrabold text-gray-900 tracking-tight leading-[1.1] mb-6">
            Get more estate cleanouts with a 5-star reputation.
          </h1>
          <p className="text-xl text-gray-500 font-medium mb-10 leading-relaxed">
            In the hauling business, fast turnarounds and trust are everything. EchoReply automates your Google review responses so you can focus on clearing properties across the Omaha area.
          </p>
          
          <div className="flex gap-4">
            <Link href="/dashboard" className="px-8 py-4 bg-indigo-600 text-white rounded-xl font-bold text-lg hover:bg-indigo-700 transition-all shadow-[0_10px_20px_rgba(79,70,229,0.2)]">
              Start Free Trial
            </Link>
          </div>
        </div>

        <div className="relative">
          <div className="absolute inset-0 bg-gradient-to-tr from-indigo-500/20 to-purple-500/20 blur-[100px] rounded-full pointer-events-none"></div>
          <div className="relative bg-white p-8 rounded-[2rem] border border-gray-100 shadow-[0_20px_50px_rgba(0,0,0,0.07)]">
            <div className="flex gap-4 mb-6 border-b border-gray-100 pb-6">
               <div className="w-12 h-12 bg-amber-100 text-amber-600 font-extrabold text-xl rounded-xl flex items-center justify-center">D</div>
               <div>
                 <h3 className="font-extrabold text-gray-900">David M.</h3>
                 <div className="text-amber-400 text-sm">★★★★★</div>
               </div>
            </div>
            <p className="text-gray-700 mb-6 font-medium">"Incredible service. They cleared out all the old junk from my garage and left the driveway spotless. Will definitely hire again!"</p>
            
            <div className="bg-indigo-50 p-5 rounded-2xl border border-indigo-100 relative">
               <p className="text-[10px] text-indigo-500 font-bold uppercase tracking-widest mb-2">Generated by EchoReply AI</p>
               <p className="text-indigo-900 font-medium text-sm">"Hi David! Thank you so much for the 5-star review. We are thrilled to hear you were happy with the garage cleanout and that we left the driveway spotless. Let us know if you need any hauling in the future!"</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}